Fix for Python3.8
camptocamp/pytest-odoo pull request #36
Opened 2020-12-03 21:40 UTC by samsagaz

Simple Fix for #35

2020-12-03 21:47 UTC, Jerther requested changes

2020-12-03 21:47 UTC, Jerther commented on pytest_odoo.py
> +    import odoo.tests:wq  # noqa
Looks like you're using VIM ;)

2020-12-03 21:49 UTC, samsagaz commented on pytest_odoo.py
> +    import odoo.tests:wq  # noqa
lol, sorry :facepalm:

2023-11-13 11:42 UTC, simahawk commented
is this still relevant?

2024-09-20 07:35 UTC, simahawk commented
feel free to reopen

2024-09-20 07:35 UTC, closed without merging