Add support for pytest 8
camptocamp/pytest-odoo pull request #65
Opened 2024-05-03 13:23 UTC by micdahl

Package and Module collection has changed in pytest 8 (see https://docs.pytest.org/en/stable/changelog.html#collection-changes). To take care of the Odoo namespaces, OdooTestModule and OdooTestPackage classes have been introduced.

2024-05-03 15:42 UTC, micdahl commented
The second commit adds --odoo-ignore-env. When this option is set, environment variables are ignored for odoo parameters. In my environment, the USER environment variable is always set automatically. This lead to problems running pytest-odoo, as my database username has always been set from the USER environment variable, instead of the Odoo config file.

2024-05-06 06:45 UTC, simahawk requested changes
Thanks for your contrib!

Don't have time right now for a full review but here are some early comments.

Moving things around altogether in the same commit does not help understanding what changed.

Any chance you could add a separated commit for the re-org in multiple files?
That would help a lot reviewers. Thanks!

2024-05-06 06:45 UTC, simahawk commented on pytest_odoo/__init__.py
> +from . import pathlib
`pathlib` and `python` do not sound like safe names

2024-05-06 18:58 UTC, micdahl commented on pytest_odoo/__init__.py
> +from . import pathlib
Hi @simahawk 
I agree with you about the names. Especially pathlib made me some headaches. But I have taken these from the pytest source. I used their names, so that one can see where the original code comes from.

2024-05-06 19:01 UTC, micdahl commented
I will do so. Will be bqck with the new commits

2024-05-07 07:14 UTC, simahawk commented on pytest_odoo/__init__.py
> +from . import pathlib
Hints:
* path_utils
* py_utils

2024-05-07 09:45 UTC, micdahl commented
I have created #66, where the changes are included in the existing pytest_odoo file. So, this pull request is closed.

2024-05-07 09:45 UTC, closed without merging